import { query } from '@/lib/db';
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';

export async function GET() {
  try {
    const session = await getServerSession();
    
    if (!session || session.user.role !== 'instructor') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get unique concepts with question counts as assessments
    const assessments = await query(`
      SELECT 
        c.concept_id as id,
        'Assessment: ' || c.concept_name as title,
        'Test your knowledge on ' || c.concept_name || ' concepts' as description,
        COUNT(q.question_id) as questionCount,
        30 as duration,
        (NOW() + INTERVAL '7 days')::date as dueDate
      FROM concepts c
      LEFT JOIN questions q ON c.concept_id = q.concept_id
      GROUP BY c.concept_id, c.concept_name
      ORDER BY c.concept_name
      LIMIT 10
    `);

    return NextResponse.json({ assessments: assessments.rows });
  } catch (error) {
    console.error('Assessments API error:', error);
    return NextResponse.json({ assessments: [] });
  }
}

export async function POST(request) {
  try {
    const session = await getServerSession();
    
    if (!session || session.user.role !== 'instructor') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Note: Assessment creation is handled by AI system
    // This endpoint is for potential future manual overrides
    return NextResponse.json({ 
      success: false, 
      message: 'Assessments are automatically generated by AI. Manual creation is not required.'
    });
  } catch (error) {
    console.error('Failed to create assessment:', error);
    return NextResponse.json({ error: 'Failed to create assessment' }, { status: 500 });
  }
}

export async function PUT(request) {
  try {
    const session = await getServerSession();
    
    if (!session || session.user.role !== 'instructor') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    return NextResponse.json({ 
      success: false, 
      message: 'Assessments are automatically managed by AI.' 
    });
  } catch (error) {
    console.error('Failed to update assessment:', error);
    return NextResponse.json({ error: 'Failed to update assessment' }, { status: 500 });
  }
}

export async function DELETE(request) {
  try {
    const session = await getServerSession();
    
    if (!session || session.user.role !== 'instructor') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    return NextResponse.json({ 
      success: false, 
      message: 'Assessments are automatically managed by AI. Manual deletion is not recommended.'
    });
  } catch (error) {
    console.error('Failed to delete assessment:', error);
    return NextResponse.json({ error: 'Failed to delete assessment' }, { status: 500 });
  }
}